baseURL = "/"
languageCode = "en-us"
title = "Reaser Interpreting"

theme = "hugo-agency"

[params]
  name = "Reaser Interpreting"
  description = "Reaser Interpreting, Professional Sign Language Interpreting Services for the Deaf & Hard-of-Hearing, located in Morgantown, WV. Committed to high standards of professional conduct, contributing to community and professional development, and facilitating linguistic and cultural communication."

  custom_css = []
  custom_js  = []
  favicon    = "img/favicon.png"

  [params.error404]
    heading = "Page couldn't be found"
    text = "Please return to [home](/)"

  [params.navigation]
    brand = "Reaser Interpreting"
    logo = "ri-logo.png"
    services = "Services"
    # portfolio = "Portfolio"
    # about = "About"
    team = "Interpreters"
    contact = "Contact"

    # [[menu.prepend]]
    #   url = "http://gohugo.io"
    #   name = "Hugo"
    #   weight = 10

    # [[menu.postpend]]
    #   url = "http://gohugo.io"
    #   name = "External link"
    #   weight = 10

  [params.hero]
    title = "Professional Sign Language Interpreters"
    subtitle = "Serving the Deaf and Hard-of-Hearing"
    buttonText = "Learn More"


  [params.services]
    enable = true
    title = "About Our Services"
    # subtitle = ""

    [[params.services.row]]

    [[params.services.row.list]]
      icon = "fa-calendar"
      title = "Flexible"
      description = "Available for a variety of settings, including educational, medical, legal, performing arts, and professional services."
      url = "#"

    [[params.services.row.list]]
      icon = "fa-briefcase"
      title = "Experienced"
      description = "15+ years of experience partnering with hearing and Deaf consumers to facilitate linguistic and cultural communication."
      url = "#"

    [[params.services.row.list]]
      icon = "fa-check-square-o"
      title = "Qualified"
      description = "All interpreters are registered via the West Virginia Registry of Interpreters (WVRI) as set forth in West Virginia State Code §192-3."
      url = "#"

      [[params.services.row.list]]
        icon = "fa-group"
        title = "Skilled"
        description = "In-depth knowledge of American Sign Language, Pidgin Sign Language, Interpreting, Transliterating, and Deaf Culture."
        url = "#"

  [params.portfolio]
    enable = false

  [params.about]
    enable = false
    title = "About"
    # subtitle = "Lorem ipsum dolor sit amet consectetur."
    # endpoint = "Be part<br>of our<br>story!"
    #
    # [[params.about.events]]
    #   img = "1.jpg"
    #   date = "2009-2011"
    #   title = "Our Humble Beginnings"
    #   description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!"
    #
    # [[params.about.events]]
    #   img = "2.jpg"
    #   date = "March 2011"
    #   title = "An Agency is Born"
    #   description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!"
    #
    # [[params.about.events]]
    #   img = "3.jpg"
    #   date = "December 2012"
    #   title = "Our Humble Beginnings"
    #   description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!"
    #
    # [[params.about.events]]
    #   img = "4.jpg"
    #   date = "July 2014"
    #   title = "Phase Two Expansion"
    #   description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!"

  [params.team]
    enable = true
    center = true
    title = "Interpreters"
    # subtitle = ""
    # description = ""

    [[params.team.members]]
      img = "reaser.jpg"
      name = "Joshua Reaser"
      position = "Sign Language Interpreter"
      # livesIn = ""
      scope = [
        "State-qualified interpreter (WVRI – State, WVRI – K12) serving the greater Morgantown, WV region."
      ]
      social = [
        ["fa-bookmark", "http://joshuareaser.com/"],
        # ["fa-facebook", "#"],
        # ["fa-linkedin", "#"]
      ]

    [params.clients_list]
      enable = false
      center = true
      #title = ""

      [[params.clients]]
        logo = "envato.jpg"
        link = "#"

      [[params.clients]]
        logo = "designmodo.jpg"
        link = "#"

      [[params.clients]]
        logo = "themeforest.jpg"
        link = "#"

      [[params.clients]]
        logo = "creative-market.jpg"
        link = "#"

  [params.contact]
    enable = true
    title = "Request Services"
    # subtitle  = ""
    buttonText = "Send Inquiry"
    email = "jreaser@reaserinterpreting.com"
    thanks = "Thank you for contacting us. We will respond to your inquiry as soon as possible."
    #error = ""

    [params.contact.form.name]
      text = "Your Name *"
      warning = "Please enter your name."

    [params.contact.form.email]
      text = "Your Email *"
      warning = "Please enter your email address."

    [params.contact.form.phone]
      text = "Your Phone *"
      warning = "Please enter your phone number."

    [params.contact.form.message]
      text = "Your Inquiry *"
      warning = "Please describe the services you are inquiring about."

      # [[params.contact.form.hidden]]
      #  name = "noshow"

  [params.footer]
    enable = true
    copyright = "Copyright 2018 by Reaser Logistics LLC"

    # [[params.footer.social]]
    #   icon = "fa-twitter"
    #   link = "#"
    #   title = "Twitter"

    # [[params.footer.social]]
    #   icon = "fa-facebook"
    #   link = "#"
    #   title = "Facebook"

    # [[params.footer.social]]
    #   icon = "fa-linkedin"
    #   link = "#"
    #   title = "LinkedIn"

    # [[params.footer.quicklinks]]
    #   text = "Privacy Policy"
    #   link = "#"

    # [[params.footer.quicklinks]]
    #   text = "Terms of Use"
    #   link = "#"
